AMS-55: Enable super admin perform CRUD operation on addresses
Amani-Labs/ams-api pull request #12
Opened 2020-03-28 00:16 UTC by Jkadhuwa

### Description
- Enable super admin to create, update, view and delete addresses

### How to test
- Clone the repo and start the server `yarn dev:watch`
- write queries on the graphql playground: `addresses` to get all addresses, `address` to retrieve a single address.
-  Run mutations to create new addresses and institution/ delete or update existing ones

Give explanations on how the reviewers can test the functionalities

### How has this been tested?

- [ ]  Unit testing
- [X]  Integration testing
- [ ]  End-to-end testing

### Any background context you want to add

### Screenshots
<img width="444" alt="Screen Shot 2020-03-28 at 03 15 48" src="https://user-images.githubusercontent.com/21122345/77809811-7d742d00-70a2-11ea-8db6-78eeac3022e3.png">
### Jira

[Finishes  AMS-55]

2020-03-28 12:27 UTC, minega25 approved these changes
LGTM

2020-03-28 12:27 UTC, minega25 commented on src/services/address.services.ts
> +    throw new Error('Address already exists! Please check your input and try again');
Is there a specific error returned from findOrCreate method that determines if the address is already in db?

2020-03-28 15:22 UTC, Jkadhuwa commented on src/services/address.services.ts
> +    throw new Error('Address already exists! Please check your input and try again');
It returns the found address and `isNewRecord` will be false.

2020-03-29 10:08 UTC, habinezadalvan commented on src/resolvers/__tests__/address.resolvers.spec.ts
> +      expect(error).toEqual(new Error('Sorry you\'re not authorized to perform this action'));
what do you think by using apollo AuthenticationError instead of Error?

2020-03-29 10:10 UTC, habinezadalvan commented on src/resolvers/__tests__/address.resolvers.spec.ts
> +      expect(error).toEqual(new Error('Address already exists! Please check your input and try again'));
When handling errors what do you think by user apollo error handlings like **AuthenticationError, ForbiddenError, UserInputError, and a generic ApolloError.**?

2020-03-29 10:22 UTC, habinezadalvan requested changes
nice work @Jkadhuwa, your work is impressive. The only comment I would give is to use Apollo error handling way.

2020-03-30 05:43 UTC, harerakalex approved these changes

2020-03-30 05:43 UTC, harerakalex approved these changes
LGTM

2020-03-30 07:43 UTC, habinezadalvan approved these changes
LGTM

2020-03-30 07:45 UTC, merged